# ===========================================
# Kubernetes Service Account
# ===========================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nikzdevz
  namespace: nikzdevz
  labels:
    app: nikzdevz
---